### ISSUE TITLE
Dynamic command options

### ISSUE THREAD

**Issue by azmeuk** [yaal-coop/scim2-cli#5]
For the sake of usage convenience, scim2-cli should provide custom commands for every models, for example on `create` and `replace` command:

```console
scim create user --user-name foo --name.formatted-name bar
```

There will be difficulties to build a simple API for multiple complex attributes, for instance I am not sure if click allows this usage:

```console
scim create user --user-name foo --email.0.value foo@bar.example --email.0.primary true --email.1.value foo@baz.example
```

At least for a start we can offer this API:

```console
scim create user --user-name foo --email "foo@bar.example,primary=true" --email "value=foo@baz.example"
```

**Comment by sblondon** [comment]
In the last example, `value` is not filled for `foo@bar.example`. With `value` key added, it would be:
```shell
scim create user --user-name foo --email "value=foo@bar.example,primary=true" --email "value foo@baz.example"
```

I wonder if there is a risk to be ambiguous without forcing key:value data.

I ignore your usecase but using a file could be another way to explore:
```shell
scim create user < user_definition
```

with `user_definition` content:
```
email.0.value=foo@bar.example
email.0.primary=true
email.1.value foo@baz.example
```

**Comment by azmeuk** [comment]
> I wonder if there is a risk to be ambiguous without forcing key:value data.

Yep, that was a typo. I meant `key=value`.

> I ignore your usecase but using a file could be another way to explore:

Currently scim2-cli uses the standard input, but expects JSON:

```console
$ scim2 create user << EOL
{
    "schemas": ["urn:ietf:params:scim:schemas:core:2.0:User"],
    "userName": "bjensen@example.com"
}
```

I think JSON is still relevant for advanced payloads, but the `--key=value` format can be useful to handle simple requests.

**Comment by azmeuk** [comment]
The *dot* separator for sub-attributes might be hard to use because of https://github.com/pallets/click/issues/2768, I think we will go with `--` instead.

```
scim create user --user-name foo --name--formatted-name bar
```

**Comment by sblondon** [comment]
From a user point of view, there are plenty hyphens to parse when writing the command line: `--` as sub attributes separator, `-`  in name attributes, and `--` for long parameters (the most obvious ones). Perhaps it could be another character like `:`:

```
scim create user --user-name foo --name:formatted-name bar
```

`:` is not a valid character in name attributes ([RFC 7643](https://www.rfc-editor.org/rfc/rfc7643), section 2.1) whereas `-` is a valid character. I thought of `:` character due to `schemas` string but another separator could match too the need (until it's not alphanumumeric, hyphen, underscore or dollar characters).

Note that I did not check how `click` manages `:` character.

**Comment by azmeuk** [comment]
I like the `:` separator!
However there is still an issue on the click side: [this method](https://github.com/pallets/click/blob/99015e1456b6952054fda8312b40ea646737168d/src/click/core.py#L2554-L2605) parses the *decls* i.e. the parameter names. Lines [2590 and 2591](https://github.com/pallets/click/blob/99015e1456b6952054fda8312b40ea646737168d/src/click/core.py#L2590-L2591), the *decl* name is expected to be a [python identifier](https://docs.python.org/3/reference/lexical_analysis.html#identifiers).

```python
>>> "name:formatted_name".isidentifier()
False
```

**Comment by azmeuk** [comment]
[pydanclick](https://github.com/felix-martel/pydanclick) is a good lead for externalizing the issue but I encountered [some issues](https://github.com/felix-martel/pydanclick/issues/created_by/azmeuk) with it at the moment.

**Comment by azmeuk** [comment]
The cleanest syntax I can think of is probably:

```console
scim create user --user-name "foobar" \
    --emails --emails-value "foo@bar.example" --primary "true" \
    --emails --emails-value "foo@baz.example"
```

Here `--emails` would just mark the creation of a new `Email` object, filled by the following `--emails-*` parameters, until a new `--emails` is met.
